"""ading new field to patient table

Revision ID: fc83416d4b34
Revises: 900d09a036a9
Create Date: 2026-02-23 16:39:11.127874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fc83416d4b34'
down_revision: Union[str, Sequence[str], None] = '900d09a036a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sex_enum = sa.Enum('man', 'woman', name='sex')
    sex_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('patients', sa.Column('sex', sa.Enum('man', 'woman', name='sex'), nullable=False))
    op.add_column('patients', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('patients', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'phone')
    op.drop_column('patients', 'age')
    op.drop_column('patients', 'sex')
    # ### end Alembic commands ###
    
    sex_enum = sa.Enum('man', 'woman', name='sex')
    sex_enum.drop(op.get_bind(), checkfirst=True)
